baseURL = "https://teddydd.me/"
languageCode = "en-us"
title = "TeddyDD"
theme = "hugo-wiki"
canonifyURLs = true
enableEmoji = true

pygmentsCodeFences = true
pygmentsStyle = "manni"
copyright = "Daniel Lewan 2017"
# RSSLink = "rss"

[author]
    name = "Daniel Lewan"

[params]
    logo = "/logo.svg"

sectionPagesMenu = "main"
[[ menu.main ]]
   name="Keybase"
   url="https://keybase.io/teddydd"
   weight = 300

[[ menu.main ]]
   name="Posts"
   url="/post/"
   identifier="post"
   weight = -300

[[ menu.main ]]
   name="Wiki"
   url="/wiki/"
   identifier="wiki"
   weight = -200