baseURL = "http://example.com/"
languageCode = "en-us"
title = "TeddyDD"
theme = "minimal"

[params]
    author = "Daniel Lewan"
    description = "Personal blog"
    githubUsername = "TeddyDD"
    accent = "#16ab6a"
    showBorder = true
    backgroundColor = "#f0f0f0"
    font = "Fira Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atom-one-light"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:vision360.daniel@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/TeddyDD/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/stillforfun/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.keybase.io/teddydd"
    name = "key"
    weight = 5
