baseURL = "https://teddydd.me/"
languageCode = "en-us"
title = "TeddyDD"
theme = "hugo-wiki"
canonifyURLs = false
relativeURLs = true
enableEmoji = true

pygmentsCodeFences = true
pygmentsStyle = "manni"
copyright = "Daniel Lewan 2017"
GoogleAnalytics = 'UA-68967687-3'
# RSSLink = "rss"

[author]
    name = "Daniel Lewan"

[params]
    logo = "/logo.svg"
    RealFaviconGenerator = true

sectionPagesMenu = "main"

[[ menu.main ]]
   name="RSS"
   url="/index.xml"
   weight = 200

[[ menu.main ]]
   name="Log"
   url="/post/"
   identifier="post"
   weight = -300

[[ menu.main ]]
   name="Wiki"
   url="/wiki/"
   identifier="wiki"
   weight = -200
